0: empId
1: lastName
2: firstName
3: middleName
4: street1
5: street2
6: city
7: state
8: zip
9: gender
10: birthDate
11: ssn
12: empStatus
13: joinedDate
14: workStation
15: location
16: workState
17: salary
18: payFrequency
19: FITWStatus
20: FITWExemptions
21: SITWState
22: SITWStatus
23: SITWExemptions
24: SUIState
25: DD1Routing
26: DD1Account
27: DD1Amount
28: DD1AmountCode
29: DD1Checking
30: DD2Routing
31: DD2Account
32: DD2Amount
33: DD2AmountCode
34: DD2Checking
