<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/07/31 10:16:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ictahrmlive',
  'username' => 'root',
  'password' => NULL,
  'port' => 3306,
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
