<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/11/24 16:40:10
sfConfig::add(array(
  'app_items_per_page' => 15,
  'app_sort_asc_class' => 'ASC',
  'app_sort_desc_class' => 'DESC',
  'app_sort_default_class' => 'null',
  'app_date_input_hint' => 'dd-mm-yy',
  'app_date_format' => 'dd-MM-yyyy',
  'app_lang_translate_status' => 'ON',
  'app_name_translate_path' => '',
));
