<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/12/03 08:26:31
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
