<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/12/10 11:46:21
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
