<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIncidentDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_dis_incidents_details');
        $this->hasColumn('dis_inc_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('dis_indetail_level', 'string', 8, array(
             'type' => 'string',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('dis_indetail_takenby', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('dis_indetail_takendate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dis_indetail_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Incidents', array(
             'local' => 'dis_inc_id',
             'foreign' => 'dis_inc_id'));
    }
}