<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEducationEMPDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_edu_emp_detail');
        $this->hasColumn('edud_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('eduh_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('subj_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('grd_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('lang_code', 'string', 13, array(
             'type' => 'string',
             'length' => '13',
             ));
        $this->hasColumn('edud_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('EducationEMPHead', array(
             'local' => 'eduh_id',
             'foreign' => 'eduh_id'));

        $this->hasOne('EducationSubject', array(
             'local' => 'subj_id',
             'foreign' => 'subj_id'));

        $this->hasOne('EducationYearGrade', array(
             'local' => 'grd_id',
             'foreign' => 'grd_id'));

        $this->hasOne('Language', array(
             'local' => 'lang_code',
             'foreign' => 'lang_code'));
    }
}