<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLeaveRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave_requests');
        $this->hasColumn('leave_request_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('leave_period_id', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('leave_type_id', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('leave_type_name', 'string', 20, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => '20',
             ));
        $this->hasColumn('date_applied', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => '25',
             ));
        $this->hasColumn('employee_id as empNumber', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'empNumber',
             'foreign' => 'empNumber'));

        $this->hasOne('LeaveType', array(
             'local' => 'leave_type_id',
             'foreign' => 'leaveTypeId'));

        $this->hasOne('LeavePeriod', array(
             'local' => 'leave_period_id',
             'foreign' => 'leavePeriodId'));

        $this->hasMany('Leave', array(
             'local' => 'leave_request_id',
             'foreign' => 'leave_request_id'));
    }
}