<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLeave extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave');
        $this->hasColumn('leave_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('leave_length_hours', 'decimal', 6, array(
             'type' => 'decimal',
             'unsigned' => '1',
             'length' => '6',
             'scale' => ' unsigned',
             ));
        $this->hasColumn('leave_length_days', 'decimal', 4, array(
             'type' => 'decimal',
             'unsigned' => '1',
             'length' => '4',
             'scale' => ' unsigned',
             ));
        $this->hasColumn('leave_request_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('leave_type_id', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('employee_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('leave_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('leave_status', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('leave_comments', 'string', 80, array(
             'type' => 'string',
             'length' => '80',
             ));
        $this->hasColumn('start_time', 'time', 25, array(
             'type' => 'time',
             'length' => '25',
             ));
        $this->hasColumn('end_time', 'time', 25, array(
             'type' => 'time',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        $this->hasOne('LeaveRequest', array(
             'local' => 'leave_request_id',
             'foreign' => 'leave_request_id'));
    }
}