<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCarderPlan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_carderplan');
        $this->hasColumn('id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('jobtit_code', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('carder_actual', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('carder_excess', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('carder_vacancies', 'integer', 100, array(
             'type' => 'integer',
             'length' => '100',
             ));
        $this->hasColumn('carder_approved', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
    }

    public function setUp()
    {
        $this->hasOne('CompanyStructure', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('JobTitle', array(
             'local' => 'jobtit_code',
             'foreign' => 'jobtit_code'));
    }
}