<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basecapability extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_sm_capability');
        $this->hasColumn('sm_capability_id', 'integer', 50, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '50',
             ));
        $this->hasColumn('sm_capability_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('sm_capability_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('sm_capability_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('sm_capability_enable_flag', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Users', array(
             'local' => 'sm_capability_id',
             'foreign' => 'sm_capability_id'));

        $this->hasMany('mnucapability', array(
             'local' => 'sm_capability_id',
             'foreign' => 'sm_capability_id'));

        $this->hasMany('ReportCapability', array(
             'local' => 'sm_capability_id',
             'foreign' => 'sm_capability_id'));
    }
}