<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayrollSchedule extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vw_hs_pr_payshedule');
        $this->hasColumn('pay_sch_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('pay_sch_st_date', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('pay_sch_end_date', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('pay_sch_processed_flg', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('pay_sch_disabled_flg', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('pay_sch_year', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('dbgroup_user_id', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('pay_sch_month', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('pay_hie_code', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '6',
             ));
    }

}