<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerformanceRate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_perf_rate');
        $this->hasColumn('rate_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('rate_code', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('rate_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('rate_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('rate_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('rate_desc', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('rate_desc_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('rate_desc_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('rate_option', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasMany('PerformanceDuty', array(
             'local' => 'rate_id',
             'foreign' => 'rate_id'));

        $this->hasMany('PerformanceRateDetails', array(
             'local' => 'rate_id',
             'foreign' => 'rate_id'));

        $this->hasMany('PerformanceEvaluation', array(
             'local' => 'rate_id',
             'foreign' => 'rate_id'));

        $this->hasMany('EvaluationCompany', array(
             'local' => 'rate_id',
             'foreign' => 'rate_id'));
    }
}