<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayrollVote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_vote_info');
        $this->hasColumn('vt_typ_code', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('vt_typ_user_code', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('vt_typ_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('vt_typ_name_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('vt_typ_name_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('vt_inf_type_code', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PayrollVoteType', array(
             'local' => 'vt_inf_type_code',
             'foreign' => 'vt_inf_type_code'));

        $this->hasMany('PayrollEmployee', array(
             'local' => 'vt_typ_code',
             'foreign' => 'vt_etf_code'));
    }
}