<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerformanceEvaluationJobRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_perf_eval_job_role');
        $this->hasColumn('eval_dtl_id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('jrl_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PerformanceEvaluationDetail', array(
             'local' => 'eval_dtl_id',
             'foreign' => 'eval_dtl_id'));

        $this->hasOne('JobRole', array(
             'local' => 'jrl_id',
             'foreign' => 'jrl_id'));
    }
}