<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLeaveHoliday extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave_holiday');
        $this->hasColumn('leave_holiday_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('leave_holiday_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('leave_holiday_name_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('leave_holiday_name_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('leave_holiday_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('leave_holiday_annual', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('leave_holiday_fulorhalf', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
    }

}