<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasehsPrProcessedtxn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_processedtxn');
        $this->hasColumn('trn_startdate', 'timestamp', null, array(
             'type' => 'timestamp',
             'primary' => true,
             ));
        $this->hasColumn('trn_enddate', 'timestamp', null, array(
             'type' => 'timestamp',
             'primary' => true,
             ));
        $this->hasColumn('trn_dtl_code', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '6',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('trn_proc_emp_amt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('trn_proc_eyr_amt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('trn_ytd_amount', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('trn_contribution', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('trn_hourswkd', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('dbgroup_user_id', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('trn_proc_emp_fullamt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('trn_ytd_eyr_amount', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('PRTransDetails', array(
             'local' => 'trn_dtl_code',
             'foreign' => 'trn_dtl_code'));
    }
}