<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basemnucapability extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_sm_mnucapability');
        $this->hasColumn('sm_capability_id', 'integer', 50, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '50',
             ));
        $this->hasColumn('sm_mnuitem_id', 'string', 50, array(
             'type' => 'string',
             'primary' => true,
             'length' => '50',
             ));
        $this->hasColumn('sm_mnucapa_save', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('sm_mnucapa_add', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('sm_mnucapa_edit', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('sm_mnucapa_delete', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        $this->hasOne('menuitem', array(
             'local' => 'sm_mnuitem_id',
             'foreign' => 'sm_mnuitem_id'));

        $this->hasOne('capability', array(
             'local' => 'sm_capability_id',
             'foreign' => 'sm_capability_id'));
    }
}