<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEBMasterDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_eb_master_detail');
        $this->hasColumn('ebd_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('ebh_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('ebs_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('ebd_pass_mark', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        $this->hasOne('EBMasterHead', array(
             'local' => 'ebh_id',
             'foreign' => 'ebh_id'));

        $this->hasOne('EBSubject', array(
             'local' => 'ebs_id',
             'foreign' => 'ebs_id'));
    }
}