<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLoanCheckList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_ln_checklist');
        $this->hasColumn('ln_chk_cat_number', 'numeric', null, array(
             'type' => 'numeric',
             'primary' => true,
             ));
        $this->hasColumn('ln_chk_number', 'numeric', null, array(
             'type' => 'numeric',
             'primary' => true,
             ));
        $this->hasColumn('ln_chk_description', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('ln_chk_is_mandatory_flg', 'numeric', 1, array(
             'type' => 'numeric',
             'length' => '1',
             ));
        $this->hasColumn('ln_chk_type_flg', 'numeric', 1, array(
             'type' => 'numeric',
             'length' => '1',
             ));
        $this->hasColumn('mo dule_code', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('formula_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('ln_chk_validate_req_flg', 'numeric', 1, array(
             'type' => 'numeric',
             'length' => '1',
             ));
        $this->hasColumn('dbgroup_user_id', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        $this->hasOne('LoanCheckListCatagory', array(
             'local' => 'ln_chk_cat_number',
             'foreign' => 'ln_chk_cat_number'));

        $this->hasMany('LoanDocument', array(
             'local' => 'ln_chk_number',
             'foreign' => 'ln_chk_number'));

        $this->hasMany('LoanGuarantee', array(
             'local' => 'ln_chk_number',
             'foreign' => 'ln_chk_number'));
    }
}