<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTrainingInstitute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_td_institute');
        $this->hasColumn('td_inst_id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '6',
             ));
        $this->hasColumn('td_inst_name_en', 'string', 75, array(
             'type' => 'string',
             'length' => '75',
             ));
        $this->hasColumn('td_inst_name_si', 'string', 75, array(
             'type' => 'string',
             'length' => '75',
             ));
        $this->hasColumn('td_inst_name_ta', 'string', 75, array(
             'type' => 'string',
             'length' => '75',
             ));
    }

    public function setUp()
    {
        $this->hasMany('TrainingCourse', array(
             'local' => 'td_inst_id',
             'foreign' => 'td_inst_id'));

        $this->hasMany('TrainingPlan', array(
             'local' => 'td_inst_id',
             'foreign' => 'td_inst_id'));
    }
}