<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLoanHeader extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_ln_header');
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('ln_app_number', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('ln_ty_number', 'decimal', 10, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('ln_hd_sequence', 'decimal', 10, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('ln_hd_amount', 'decimal', 18, array(
             'type' => 'decimal',
             'length' => '18',
             'scale' => '2',
             ));
        $this->hasColumn('ln_hd_bal_amount', 'decimal', 18, array(
             'type' => 'decimal',
             'length' => '18',
             'scale' => '2',
             ));
        $this->hasColumn('ln_hd_installment', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('ln_hd_is_active_flg', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('ln_hd_settled_flg', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('ln_hd_user', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('ln_hd_apply_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ln_hd_bal_installment', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('app_approved', 'numeric', 1, array(
             'type' => 'numeric',
             'length' => '1',
             ));
        $this->hasColumn('wfmain_id', 'varchar', 6, array(
             'type' => 'varchar',
             'length' => '6',
             ));
        $this->hasColumn('ln_hd_lst_proc_to_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('wfmain_sequence', 'numeric', null, array(
             'type' => 'numeric',
             ));
        $this->hasColumn('ln_hd_lst_proc_from_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ln_hd_effective_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ln_hd_inactive_period', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('ln_hd_install_amount', 'numeric', 13, array(
             'type' => 'numeric',
             'length' => '13',
             'scale' => '2',
             ));
        $this->hasColumn('dbgroup_user_id', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ln_hd_app_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('cancel_approved', 'numeric', 5, array(
             'type' => 'numeric',
             'length' => '5',
             ));
        $this->hasColumn('cancel_main_id', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));
    }

    public function setUp()
    {
        $this->hasOne('LoanType', array(
             'local' => 'ln_ty_number',
             'foreign' => 'ln_ty_number'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('LoanApplication', array(
             'local' => 'ln_app_number',
             'foreign' => 'ln_app_number'));
    }
}