<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCompanyStructure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_compstructtree');
        $this->hasColumn('comp_code', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('title_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('title_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('parnt', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('comp_address as address', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('comp_address_si as address_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('comp_address_ta as address_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('comp_phone_intercom as phone_intercom', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('comp_phone_vip as phone_vip', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('comp_phone_direct_line as phone_direct_line', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('comp_phone_extension as phone_extension', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('comp_fax as fax', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('comp_email as email', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('comp_url as url', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('def_level', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('comp_location_code', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('comp_reference_code', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('comp_isfunctional', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Employee as employees', array(
             'local' => 'id',
             'foreign' => 'work_station'));

        $this->hasOne('Employee as divisionHead', array(
             'local' => 'emp_number',
             'foreign' => 'empNumber'));

        $this->hasMany('Transfer as transfer', array(
             'local' => 'id',
             'foreign' => 'trans_div_id'));

        $this->hasOne('CompanyStructureLevels', array(
             'local' => 'def_level',
             'foreign' => 'def_level'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'id',
             'foreign' => 'work_station'));

        $this->hasMany('CompanyStructureDetails', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('Transfer', array(
             'local' => 'id',
             'foreign' => 'trans_currentdiv_id'));

        $this->hasMany('Promotion', array(
             'local' => 'id',
             'foreign' => 'prm_divition'));

        $this->hasMany('TransferRequest', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('CarderPlan', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('VacancyRequisition', array(
             'local' => 'id',
             'foreign' => 'cmp_stur_id'));

        $this->hasMany('Reinstatement', array(
             'local' => 'id',
             'foreign' => 'work_station'));

        $this->hasMany('EmpActiveWorkstation', array(
             'local' => 'id',
             'foreign' => 'act_hie_code_1'));

        $this->hasMany('hsPrBankDisketteProcess', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('payprocessCapability', array(
             'local' => 'id',
             'foreign' => 'prl_disc_code'));
    }
}