<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmployeeStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_empstat');
        $this->hasColumn('estat_code as id', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('estat_name as name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('estat_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('estat_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Employee as employees', array(
             'local' => 'estat_code',
             'foreign' => 'emp_status'));

        $this->hasMany('JobTitle as jobTitles', array(
             'refClass' => 'JobTitleEmployeeStatus',
             'local' => 'estat_code',
             'foreign' => 'jobtit_code'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'estat_code',
             'foreign' => 'emp_status'));

        $this->hasMany('JobTitleEmployeeStatus', array(
             'local' => 'id',
             'foreign' => 'estat_code'));

        $this->hasMany('Promotion', array(
             'local' => 'estat_code',
             'foreign' => 'estat_code'));

        $this->hasMany('LeaveTypeConfigDetail', array(
             'local' => 'id',
             'foreign' => 'estat_code'));

        $this->hasMany('VacancyRequisition', array(
             'local' => 'estat_code',
             'foreign' => 'estat_code'));
    }
}