<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayRollBank extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_bank');
        $this->hasColumn('bank_code', 'string', 8, array(
             'type' => 'string',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('bank_user_code', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bank_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bank_name_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bank_name_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bank_address', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bank_address_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bank_address_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bnk_main', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('bnk_mainbank', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
        $this->hasColumn('acc_fmt_code', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 0,
             'length' => '10',
             ));
        $this->hasColumn('acc_no_lng', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 0,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PayRollBankAccFormat', array(
             'local' => 'acc_fmt_code',
             'foreign' => 'acc_fmt_code'));

        $this->hasOne('PayRollBankAccountType as accFmtCode', array(
             'local' => 'acc_fmt_code',
             'foreign' => 'acc_fmt_code'));

        $this->hasMany('PRTransDetails', array(
             'local' => 'bank_code',
             'foreign' => 'bank_code'));

        $this->hasMany('PayRollBranch', array(
             'local' => 'bank_code',
             'foreign' => 'bank_code'));

        $this->hasMany('PayRollBankTransfer', array(
             'local' => 'bank_code',
             'foreign' => 'bank_code'));

        $this->hasMany('hsPrBankDiskette', array(
             'local' => 'bank_code',
             'foreign' => 'bank_code'));
    }
}