<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePromotionChecklistDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_promotion_ckecklist_detail');
        $this->hasColumn('emp_number', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('prm_checklist_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('prm_value', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('prm_complete_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('prm_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('prm_ovr_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('PromotionCkecklist', array(
             'local' => 'prm_checklist_id',
             'foreign' => 'prm_checklist_id'));
    }
}