<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLeavePeriod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave_period');
        $this->hasColumn('leave_period_id as leavePeriodId', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('leave_period_start_date as startDate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('leave_period_end_date as endDate', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        $this->hasMany('LeaveRequest', array(
             'local' => 'leavePeriodId',
             'foreign' => 'leave_period_id'));

        $this->hasMany('EmployeeLeaveEntitlement', array(
             'local' => 'leavePeriodId',
             'foreign' => 'leave_period_id'));

        $this->hasMany('EmployeeLeaveAccrual', array(
             'local' => 'leavePeriodId',
             'foreign' => 'leave_period_id'));
    }
}