<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayRollEligibility extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_txn_eligibility');
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('trn_dtl_code', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '6',
             ));
        $this->hasColumn('trn_dtl_startdate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('trn_dtl_enddate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('tre_amount', 'decimal', 13, array(
             'type' => 'decimal',
             'length' => '13',
             'scale' => '2',
             ));
        $this->hasColumn('tre_last_modified_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('tre_user_id', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
        $this->hasColumn('tre_stop_flag', 'decimal', 1, array(
             'type' => 'decimal',
             'length' => '1',
             ));
        $this->hasColumn('tre_empcon', 'decimal', 13, array(
             'type' => 'decimal',
             'length' => '13',
             'scale' => '2',
             ));
        $this->hasColumn('tre_eyrcon', 'decimal', 13, array(
             'type' => 'decimal',
             'length' => '13',
             'scale' => '2',
             ));
        $this->hasColumn('tre_hours', 'decimal', 8, array(
             'type' => 'decimal',
             'length' => '8',
             'scale' => '2',
             ));
        $this->hasColumn('dbgroup_user_id', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('PRTransDetails', array(
             'local' => 'trn_dtl_code',
             'foreign' => 'trn_dtl_code'));
    }
}