<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseGrade extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_grade');
        $this->hasColumn('grade_code', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('grade_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('grade_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('grade_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Employee', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));

        $this->hasMany('GradeSlot', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));

        $this->hasMany('Promotion', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));

        $this->hasMany('EBExam', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));

        $this->hasMany('VacancyRequisition', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));

        $this->hasMany('PayrollIncrement', array(
             'local' => 'grade_code',
             'foreign' => 'inc_previous_grade_code'));

        $this->hasMany('Reinstatement', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));

        $this->hasMany('PayrollIncrementCancel', array(
             'local' => 'grade_code',
             'foreign' => 'inc_previous_grade_code'));

        $this->hasMany('EBMasterHead', array(
             'local' => 'grade_code',
             'foreign' => 'grade_code'));
    }
}