<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseJobTitle extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_job_title');
        $this->hasColumn('jobtit_code as id', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('jobtit_name as name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('jobtit_name_si as name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('jobtit_name_ta as name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Employee as employees', array(
             'local' => 'jobtit_code',
             'foreign' => 'job_title_code'));

        $this->hasMany('EmployeeStatus as employeeStatuses', array(
             'refClass' => 'JobTitleEmployeeStatus',
             'local' => 'jobtit_code',
             'foreign' => 'estat_code'));

        $this->hasMany('JobTitleEmployeeStatus', array(
             'local' => 'id',
             'foreign' => 'jobtit_code'));

        $this->hasOne('CarderPlan', array(
             'local' => 'jobtit_code',
             'foreign' => 'jobtit_code'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'jobtit_code',
             'foreign' => 'job_title_code'));

        $this->hasMany('Promotion', array(
             'local' => 'jobtit_code',
             'foreign' => 'jobtit_code'));

        $this->hasMany('JobRole', array(
             'local' => 'jobtit_code',
             'foreign' => 'jobtit_code'));

        $this->hasMany('PerformanceEvaluationDetail', array(
             'local' => 'jobtit_code',
             'foreign' => 'jobtit_code'));

        $this->hasMany('VacancyRequisition', array(
             'local' => 'jobtit_code',
             'foreign' => 'jobtit_code'));

        $this->hasMany('Reinstatement', array(
             'local' => 'jobtit_code',
             'foreign' => 'job_title_code'));

        $this->hasMany('EmpActiveWorkstation', array(
             'local' => 'jobtit_code',
             'foreign' => 'act_job_title_code'));
    }
}