<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAdvertisementAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_rec_adv_attachment');
        $this->hasColumn('rec_adv_attach_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('rec_adv_attach_filename', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('rec_adv_attach_size', 'string', 11, array(
             'type' => 'string',
             'length' => '11',
             ));
        $this->hasColumn('rec_adv_attach_attachment', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => '2147483647',
             ));
        $this->hasColumn('rec_adv_attach_type', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('rec_adv_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Advertisement', array(
             'local' => 'rec_adv_id',
             'foreign' => 'rec_adv_id'));
    }
}