<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseWeekends extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_weekends');
        $this->hasColumn('day', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('length', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

}