<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOtherInstitute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_other_institute');
        $this->hasColumn('oth_inst_id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('oth_institute_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('oth_release_location', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('oth_release_from', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('oth_release_to', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('oth_payroll_active_flg', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('oth_reason', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}