<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEMPEBExam extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_ebexam');
        $this->hasColumn('ebexam_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('employee_id', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('emp_ebexam_duedate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('emp_ebexam_completedate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('emp_ebexam_status', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('emp_ebexam_remarks', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('emp_ebexam_genaralcomment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('EBExam', array(
             'local' => 'ebexam_id',
             'foreign' => 'ebexam_id'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}