<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAttendanceClockDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_atn_clockdown');
        $this->hasColumn('clk_no', 'string', 20, array(
             'type' => 'string',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('clk_date', 'date', 25, array(
             'type' => 'date',
             'primary' => true,
             'length' => '25',
             ));
        $this->hasColumn('clk_time', 'time', 25, array(
             'type' => 'time',
             'primary' => true,
             'length' => '25',
             ));
        $this->hasColumn('clk_status', 'string', 2, array(
             'type' => 'string',
             'length' => '2',
             ));
        $this->hasColumn('clk_move', 'string', 5, array(
             'type' => 'string',
             'length' => '5',
             ));
    }

}