<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDisEmployeeInvolved extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_dis_involved_emp');
        $this->hasColumn('dis_inc_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('dis_inv_type', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('dis_fna_code', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Incidents', array(
             'local' => 'dis_inc_id',
             'foreign' => 'dis_inc_id'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('DisiplinaryFinalAction', array(
             'local' => 'dis_fna_code',
             'foreign' => 'dis_fna_code'));
    }
}