<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerformanceRateDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_perf_rate_detail');
        $this->hasColumn('rate_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('rdt_grade', 'string', 10, array(
             'type' => 'string',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('rdt_mark', 'float', 2147483647, array(
             'type' => 'float',
             'primary' => true,
             'length' => '2147483647',
             ));
        $this->hasColumn('rdt_description', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PerformanceRate', array(
             'local' => 'rate_id',
             'foreign' => 'rate_id'));
    }
}