<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOffenceList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_dis_offence_list');
        $this->hasColumn('dis_inc_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('dis_offence_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Incidents', array(
             'local' => 'dis_inc_id',
             'foreign' => 'dis_inc_id'));

        $this->hasOne('Offence', array(
             'local' => 'dis_offence_id',
             'foreign' => 'dis_offence_id'));
    }
}