<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseWorkShift extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_workshift');
        $this->hasColumn('workshift_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '250',
             ));
        $this->hasColumn('hours_per_day', 'decimal', 4, array(
             'type' => 'decimal',
             'notnull' => true,
             'scale' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasMany('EmployeeWorkShift', array(
             'local' => 'workshift_id',
             'foreign' => 'workshift_id'));
    }
}