<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTrainingCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_td_course');
        $this->hasColumn('td_course_id', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '6',
             ));
        $this->hasColumn('td_inst_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('td_course_code', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('td_course_year', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('td_course_name_en', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('td_course_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('td_course_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('lang_code', 'string', 13, array(
             'type' => 'string',
             'length' => '13',
             ));
        $this->hasColumn('td_course_venue_en', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_venue_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_venue_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_fromdate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('td_course_todate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('td_course_fromtime', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('td_course_totime', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('td_course_objective_en', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_objective_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_objective_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_whom_en', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_whom_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_whom_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_content_en', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_content_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_content_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_gencom_en', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_gencom_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_gencom_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('td_course_fees', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('td_course_fees_per_head', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('td_course_fees_additional', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('level_code', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('td_course_resouse_person', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('td_approval_type', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasOne('TrainingInstitute', array(
             'local' => 'td_inst_id',
             'foreign' => 'td_inst_id'));

        $this->hasOne('Language', array(
             'local' => 'lang_code',
             'foreign' => 'lang_code'));

        $this->hasOne('Level', array(
             'local' => 'level_code',
             'foreign' => 'level_code'));

        $this->hasMany('TrainingPlan', array(
             'local' => 'td_course_id',
             'foreign' => 'td_course_id'));

        $this->hasMany('TrainAssign', array(
             'local' => 'td_course_id',
             'foreign' => 'td_course_id'));
    }
}