<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAudit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_disciaction');
        $this->hasColumn('audit_id', 'float', null, array(
             'type' => 'float',
             'primary' => true,
             ));
        $this->hasColumn('audit_table_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('audit_row_pk', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('audit_field_name', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('audit_old_value', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => '2147483647',
             ));
        $this->hasColumn('audit_new_value', 'blob', 2147483647, array(
             'type' => 'blob',
             'length' => '2147483647',
             ));
        $this->hasColumn('audit_datetime', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('audit_user', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
        $this->hasColumn('audit_description', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

}