<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLeaveApplication extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave_application');
        $this->hasColumn('leave_app_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('leave_app_applied_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('leave_app_start_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('leave_app_end_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('leave_app_status', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('leave_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('leave_app_reason', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('leave_app_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('leave_type_wf_id', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('leave_app_covemp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('leave_app_workdays', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('Employee as cEmployee', array(
             'local' => 'leave_app_covemp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('LeaveType', array(
             'local' => 'leave_type_id',
             'foreign' => 'leave_type_id'));

        $this->hasOne('LeaveTypeConfig', array(
             'local' => 'leave_type_wf_id',
             'foreign' => 'leave_type_wf_id'));

        $this->hasOne('LeaveDetail', array(
             'local' => 'leave_app_id',
             'foreign' => 'leave_app_id'));

        $this->hasMany('Attendance', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}