<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLeaveDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave_details');
        $this->hasColumn('leave_app_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('leave_app_applied_date', 'date', 25, array(
             'type' => 'date',
             'primary' => true,
             'length' => '25',
             ));
        $this->hasColumn('leave_dtl_amount', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('leave_dtl_type', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasOne('LeaveApplication', array(
             'local' => 'leave_app_id',
             'foreign' => 'leave_app_id'));
    }
}