<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRecVacancyRequest extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_rec_vacancy_request');
        $this->hasColumn('rec_vac_req_id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '7',
             ));
        $this->hasColumn('rec_vac_vacancy_title', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '100',
             ));
        $this->hasColumn('rec_vac_vacancy_title_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('rec_vac_vacancy_title_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('rec_vac_ref_number', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('rec_vac_year', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '3',
             ));
        $this->hasColumn('rec_vac_no_of_vacancies', 'integer', 7, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '7',
             ));
        $this->hasColumn('rec_vac_is_submit', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('rec_vac_hr_approved_flag', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
        $this->hasColumn('rec_vac_dg_approved_flag', 'integer', 2, array(
             'type' => 'integer',
             'length' => '2',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}