<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmployeeEducation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_education');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('edu_code', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('edu_institute', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_institute_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_institute_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_stream', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_stream_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_stream_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_index_no', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('edu_start_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('edu_end_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('edu_year', 'decimal', 4, array(
             'type' => 'decimal',
             'length' => '4',
             ));
        $this->hasColumn('edu_confirmed_flg', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('Education', array(
             'local' => 'edu_code',
             'foreign' => 'edu_code'));

        $this->hasOne('EmployeeMaster', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}