<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseOfficeOut extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave_office_out');
        $this->hasColumn('oo_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('oo_emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('oo_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('oo_to_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('oo_from', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('oo_to', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('oo_category', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('oo_comment', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('oo_vehicle_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('oo_cancel', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('oo_authority', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'oo_emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('OfficeOutDetails', array(
             'local' => 'oo_id',
             'foreign' => 'oo_id'));
    }
}