<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerformanceEvaluationDuty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_perf_eval_duty');
        $this->hasColumn('eval_dtl_id', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('dut_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('dut_weightage', 'string', 10, array(
             'type' => 'string',
             'primary' => true,
             'length' => '10',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PerformanceEvaluationDetail', array(
             'local' => 'eval_dtl_id',
             'foreign' => 'eval_dtl_id'));

        $this->hasOne('PerformanceDuty', array(
             'local' => 'dut_id',
             'foreign' => 'dut_id'));
    }
}