<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCompanyStructureLevels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_company_structure_def');
        $this->hasColumn('def_level', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('def_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('def_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('def_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('CompanyStructure', array(
             'local' => 'def_level',
             'foreign' => 'def_level'));

        $this->hasMany('Users', array(
             'local' => 'def_level',
             'foreign' => 'def_level'));

        $this->hasMany('TransferRequest', array(
             'local' => 'def_level',
             'foreign' => 'def_level'));
    }
}