<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseWfAppPerson extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_wf_approval_person');
        $this->hasColumn('wfapper_decription', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('wfapper_code', 'string', 20, array(
             'type' => 'string',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('wfapper_sqlquery', 'string', 2000, array(
             'type' => 'string',
             'length' => '2000',
             ));
        $this->hasColumn('wfapper_is_group_flg', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
    }

    public function setUp()
    {
        $this->hasOne('WfApproval', array(
             'local' => 'wfapper_code',
             'foreign' => 'wfapper_code'));
    }
}