<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseWfApproval extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_wf_approvel');
        $this->hasColumn('wftype_code', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('wfa_sequence', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '20',
             ));
        $this->hasColumn('wfapper_code', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wfapper_iscompulsory_flg', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('wfapper_lastlevel', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('wfapper_allowchange', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
    }

    public function setUp()
    {
        $this->hasMany('WfAppPerson', array(
             'local' => 'wfapper_code',
             'foreign' => 'wfapper_code'));
    }
}