<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasehsPrBankDisketteProcess extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_bank_diskette_process');
        $this->hasColumn('bdp_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('dsk_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('bdp_start_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('bdp_end_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('bdp_payment_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('bdp_processed', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('bdp_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('bdp_payment_total', 'decimal', 13, array(
             'type' => 'decimal',
             'length' => '13',
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        $this->hasOne('CompanyStructure', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('hsPrBankDiskette', array(
             'local' => 'dsk_id',
             'foreign' => 'dsk_id'));
    }
}