<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayrollProcessBar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_progressbar_status');
        $this->hasColumn('pb_user', 'string', 36, array(
             'type' => 'string',
             'primary' => true,
             'length' => '36',
             ));
        $this->hasColumn('pb_startdate', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('pb_enddate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('pb_emp_total_count', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('prl_type_code', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('pb_processtime', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('pb_emp_remain_count', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('pb_status', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

}