<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseWftype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_wf_type');
        $this->hasColumn('wftype_description', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('wftype_code', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('wftype_table_name', 'string', 11, array(
             'type' => 'string',
             'length' => '11',
             ));
        $this->hasColumn('wftype_view_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('wfmod_id', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wftype_class', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wftype_method_name', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wftype_redirect_url', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('wftype_canclemain_field', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wftype_canclestatus_field', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wftype_appmain_field', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wftype_bulk_app_flg', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('wftype_sort_field_name', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        $this->hasOne('WfModule', array(
             'local' => 'wfmod_id',
             'foreign' => 'wfmod_id'));

        $this->hasOne('WfMain', array(
             'local' => 'wftype_code',
             'foreign' => 'wftype_code'));
    }
}