<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayRollContributeBase extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_contribution_base');
        $this->hasColumn('trn_dtl_code', 'integer', 6, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '6',
             ));
        $this->hasColumn('trn_dtl_base_code', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('dbgroup_user_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('trn_contribute_code', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PRTransDetails', array(
             'local' => 'trn_dtl_code',
             'foreign' => 'trn_dtl_code'));
    }
}