<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNotice extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_notice');
        $this->hasColumn('notice_code', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('notice_name', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('notice_name_si', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('notice_name_ta', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('notice_desc', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('notice_desc_si', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('notice_desc_ta', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
        $this->hasColumn('from_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('to_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('email_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('sms_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('sms_text', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('create_emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('create_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('create_time', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'create_emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('NoticeEmployee', array(
             'local' => 'notice_code',
             'foreign' => 'notice_code'));
    }
}