<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLDAPAudit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_ldap_audit');
        $this->hasColumn('ldap_adt_employeeid', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_firstname', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_firstnamesi', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_firstnameta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_lastname', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_lastnamesi', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_lastnameta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_designationcode', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_districtcode', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_divisioncode', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_zonecode', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_wasamcode', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_employeeactiveflag', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_departmentcode', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_email', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_cn', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_sn', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_emp_number', 'string', 200, array(
             'type' => 'string',
             'primary' => true,
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_userid', 'string', 200, array(
             'type' => 'string',
             'primary' => true,
             'length' => '200',
             ));
        $this->hasColumn('ldap_adt_datetime', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
    }

}