<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseIncidents extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_dis_incidents');
        $this->hasColumn('dis_inc_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('dis_acttype_id', 'integer', 8, array(
             'type' => 'integer',
             'length' => '8',
             ));
        $this->hasColumn('dis_inc_level', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('dis_inc_isclosed', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('dis_inc_inq_officer', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_pro_officer', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_defe_officer', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_filedate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dis_inc_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dis_inc_time', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_incident', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_incident_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_incident_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_reportedby', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_prelim_com', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_finact_tknby', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_finact_tkn', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_type', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('dis_inc_prim_summary', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_finact_tkndate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('dis_inc_reporteddate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('dis_inc_reportedtime', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_todate', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('dis_inc_totime', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dis_inc_major_mionor_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dis_inc_investigation_auditfb', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_ifchargesheetissued_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dis_inc_chargesheet_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_caseclosed_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_furtheraction_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dis_inc_furtheraction_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_intedicted_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dis_inc_intedicted_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_inquery_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_fna_code', 'integer', 10, array(
             'type' => 'integer',
             'length' => '10',
             ));
        $this->hasColumn('dis_inc_finalaction_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_appeal_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dis_inc_appeal_date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('dis_inc_appeal_board_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_inc_appeal_labour_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('DisciplinaryActionType', array(
             'local' => 'dis_acttype_id',
             'foreign' => 'dis_acttype_id'));

        $this->hasOne('DisAttachment', array(
             'local' => 'dis_attach_id',
             'foreign' => 'dis_attach_id'));

        $this->hasOne('Offence', array(
             'local' => 'dis_offence_id',
             'foreign' => 'dis_offence_id'));

        $this->hasOne('Employee', array(
             'local' => 'dis_inc_reportedby',
             'foreign' => 'emp_number'));

        $this->hasOne('DisEmployeeInvolved', array(
             'local' => 'dis_inc_id',
             'foreign' => 'dis_inc_id'));

        $this->hasOne('DisiplinaryFinalAction', array(
             'local' => 'dis_fna_code',
             'foreign' => 'dis_fna_code'));

        $this->hasMany('IncidentDetails', array(
             'local' => 'dis_inc_id',
             'foreign' => 'dis_inc_id'));

        $this->hasMany('OffenceList', array(
             'local' => 'dis_inc_id',
             'foreign' => 'dis_inc_id'));
    }
}