<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLoanProcessed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_ln_processed_loan');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('ln_hd_sequence', 'decimal', 10, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('ln_sch_ins_no', 'decimal', 10, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('ln_ty_number', 'decimal', 10, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('ln_processed_from_date', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('ln_processed_to_date', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('ln_processed_capital', 'decimal', 18, array(
             'type' => 'decimal',
             'length' => '18',
             ));
        $this->hasColumn('ln_processed_interest', 'decimal', 18, array(
             'type' => 'decimal',
             'length' => '18',
             ));
        $this->hasColumn('ln_interest_rate', 'decimal', 13, array(
             'type' => 'decimal',
             'length' => '13',
             ));
        $this->hasColumn('dbgroup_user_id', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('ln_bal_installment', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => '10',
             ));
        $this->hasColumn('ln_bal_amount', 'decimal', 18, array(
             'type' => 'decimal',
             'length' => '18',
             ));
    }

    public function setUp()
    {
        $this->hasOne('LoanType', array(
             'local' => 'ln_ty_number',
             'foreign' => 'ln_ty_number'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('LoanApplication', array(
             'local' => 'ln_app_number',
             'foreign' => 'ln_app_number'));
    }
}