<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmpClass extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_class');
        $this->hasColumn('class_code', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('class_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('class_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('class_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Employee', array(
             'local' => 'class_code',
             'foreign' => 'class_code'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'class_code',
             'foreign' => 'class_code'));

        $this->hasMany('Promotion', array(
             'local' => 'class_code',
             'foreign' => 'class_code'));
    }
}