<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTransferType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_trans_type');
        $this->hasColumn('trans_type_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('trans_type_en', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('trans_type_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('trans_type_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Transfer', array(
             'local' => 'trans_type_id',
             'foreign' => 'trans_type_id'));
    }
}