<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmpEmergencyContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_emergency_contacts');
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('eec_seqno as seqno', 'decimal', 2, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => '2',
             ));
        $this->hasColumn('eec_name as name', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_name_si as name_si', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_name_ta as name_ta', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_relationship as relationship', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_relationship_si as relationship_si', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_relationship_ta as relationship_ta', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_address as address', 'string', 200, array(
             'type' => 'string',
             'default' => '',
             'length' => '200',
             ));
        $this->hasColumn('eec_address_si as address_si', 'string', 200, array(
             'type' => 'string',
             'default' => '',
             'length' => '200',
             ));
        $this->hasColumn('eec_address_ta as address_ta', 'string', 200, array(
             'type' => 'string',
             'default' => '',
             'length' => '200',
             ));
        $this->hasColumn('eec_home_no as home_phone', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_mobile_no as mobile_phone', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
        $this->hasColumn('eec_office_no as office_phone', 'string', 100, array(
             'type' => 'string',
             'default' => '',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('EmployeeMaster', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}