<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDisiplinaryFinalAction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_dis_finalaction');
        $this->hasColumn('dis_fna_code', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '10',
             ));
        $this->hasColumn('dis_fna_usercode', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('dis_fna_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_fna_name_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_fna_name_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dis_fna_type', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasMany('DisEmployeeInvolved', array(
             'local' => 'dis_fna_code',
             'foreign' => 'dis_fna_code'));

        $this->hasMany('Incidents', array(
             'local' => 'dis_fna_code',
             'foreign' => 'dis_fna_code'));
    }
}