<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasehsPrBankDisketteDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_bank_diskette_detail');
        $this->hasColumn('dskd_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('dsk_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('dskd_column', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dskd_length', 'string', 4, array(
             'type' => 'string',
             'length' => '4',
             ));
        $this->hasColumn('dskd_type', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dskd_alignment', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dskd_fillwith', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dskd_value', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('dskd_order', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('dskd_active', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('dsk_detail_type', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasOne('hsPrBankDiskette', array(
             'local' => 'dsk_id',
             'foreign' => 'dsk_id'));
    }
}