<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePerformanceEvaluationEmployeeDuty extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_perf_eval_employee_duty');
        $this->hasColumn('eval_dtl_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('dut_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('eval_duty_rate', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('eval_duty_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PerformanceEvaluationDetail', array(
             'local' => 'eval_dtl_id',
             'foreign' => 'eval_dtl_id'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('PerformanceDuty', array(
             'local' => 'dut_id',
             'foreign' => 'dut_id'));
    }
}