<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEBSubject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_eb_subject');
        $this->hasColumn('ebs_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('ebs_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ebs_name_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ebs_name_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasMany('EBMasterDetail', array(
             'local' => 'ebs_id',
             'foreign' => 'ebs_id'));
    }
}