<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmployeeLicense extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_licenses');
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('lic_seqno', 'decimal', 2, array(
             'type' => 'decimal',
             'primary' => true,
             'length' => '2',
             ));
        $this->hasColumn('lic_number', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('lic_type', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('lic_type_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('lic_type_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('lic_issue_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('lic_expiry_date', 'date', null, array(
             'type' => 'date',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'empNumber',
             'foreign' => 'empNumber'));

        $this->hasOne('EmployeeMaster', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('Licenses', array(
             'local' => 'licenses_code',
             'foreign' => 'licenses_code'));
    }
}