<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayRollProcessedEmp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_processedemp');
        $this->hasColumn('pro_payfrequency', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('pro_startdate', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('pro_enddate', 'date', null, array(
             'type' => 'date',
             'primary' => true,
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('pro_processed', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('pro_inserttime', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('pro_batch_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}