<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBenifitType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_wbm_benifit_type');
        $this->hasColumn('bt_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('bt_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bt_name_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('bt_name_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasMany('BenifitSubType', array(
             'local' => 'bt_id',
             'foreign' => 'bt_id'));

        $this->hasMany('Benifit', array(
             'local' => 'bt_id',
             'foreign' => 'bt_id'));
    }
}