<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasehsPrPayprocess extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_pr_payprocess');
        $this->hasColumn('pay_startdate', 'timestamp', null, array(
             'type' => 'timestamp',
             'primary' => true,
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('pay_enddate', 'timestamp', null, array(
             'type' => 'timestamp',
             'primary' => true,
             ));
        $this->hasColumn('pay_gross_salary', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_netpay', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_gross_salary_ytd', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_netpay_ytd', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_dsg_code', 'string', 13, array(
             'type' => 'string',
             'length' => '13',
             ));
        $this->hasColumn('pay_last_level_hie_code', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('pay_cash_paid_amt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_bank_paid_amt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_paid_salary', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_grossnet_amt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_cf_amt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_bf_amt', 'decimal', 13, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '13',
             ));
        $this->hasColumn('pay_emp_comnt', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('pay_hie_code_1', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('pay_salary_point', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 0,
             'length' => '10',
             ));
        $this->hasColumn('pay_hie_code_2', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('pay_hie_code_6', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('pay_hie_code_4', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('pay_hie_code_3', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('pay_hie_code_5', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('pay_costcenter', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));
        $this->hasColumn('emp_epf_number', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('pay_emp_type', 'string', 13, array(
             'type' => 'string',
             'length' => '13',
             ));
        $this->hasColumn('pay_salarygrade', 'string', 6, array(
             'type' => 'string',
             'length' => '6',
             ));
        $this->hasColumn('pay_processed_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('pay_proc_user', 'string', 150, array(
             'type' => 'string',
             'length' => '150',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}