<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEvaluationTSEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_evl_ts_emp');
        $this->hasColumn('emp_ts_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('eval_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('ts_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('emp_ts_from_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('emp_ts_to_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('emp_ts_active_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('emp_ts_approve_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('emp_ts_target_indicater', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('emp_ts_sup_comment', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('emp_ts_mod_comment', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('emp_ts_sup_mid_achive', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_sup_end_achive', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_sup_mid_marks', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_sup_end_marks', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_mod_end_marks', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_mod_end_achive', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_weight', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_email_client_1', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('emp_ts_send_url_client_1', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('emp_ts_marks_client_1', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_send_url_date_client_1', 'DateTime', null, array(
             'type' => 'DateTime',
             ));
        $this->hasColumn('emp_ts_email_client_2', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('emp_ts_send_url_client_2', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('emp_ts_marks_client_2', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_send_url_date_client_2', 'DateTime', null, array(
             'type' => 'DateTime',
             ));
        $this->hasColumn('emp_ts_email_client_3', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('emp_ts_send_url_client_3', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('emp_ts_marks_client_3', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_send_url_date_client_3', 'DateTime', null, array(
             'type' => 'DateTime',
             ));
        $this->hasColumn('emp_ts_email_client_4', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('emp_ts_send_url_client_4', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('emp_ts_marks_client_4', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_send_url_date_client_4', 'DateTime', null, array(
             'type' => 'DateTime',
             ));
        $this->hasColumn('emp_ts_email_client_5', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('emp_ts_send_url_client_5', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('emp_ts_marks_client_5', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('emp_ts_send_url_date_client_5', 'DateTime', null, array(
             'type' => 'DateTime',
             ));
        $this->hasColumn('emp_ts_marks_client_summary', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
    }

    public function setUp()
    {
        $this->hasOne('EvaluationCompany', array(
             'local' => 'eval_id',
             'foreign' => 'eval_id'));

        $this->hasOne('EmployeeMaster as Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('EvaluationTSMaster', array(
             'local' => 'ts_id',
             'foreign' => 'ts_id'));

        $this->hasMany('EvaluationTSEmployeeComments', array(
             'local' => 'emp_ts_id',
             'foreign' => 'emp_ts_id'));
    }
}