<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEvaluationSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_evl_skill_master');
        $this->hasColumn('skill_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('skill_title', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('skill_title_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('skill_title_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('skill_description', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('skill_description_si', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('skill_description_ta', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('skill_active_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasMany('EvaluationSkillEmployee', array(
             'local' => 'skill_id',
             'foreign' => 'skill_id'));
    }
}