<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEvaluationFunctionsTask extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_evl_functions_tasks');
        $this->hasColumn('ft_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('eval_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('ft_title', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ft_description', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('ft_from_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ft_to_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ft_active_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('ft_approve_flg', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('ft_target_indicater', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('ft_sup_comment', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('ft_mod_comment', 'string', 500, array(
             'type' => 'string',
             'length' => '500',
             ));
        $this->hasColumn('ft_sup_mid_achive', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('ft_sup_end_achive', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('ft_sup_mid_marks', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('ft_sup_end_marks', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('ft_mod_end_achive', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('ft_mod_end_marks', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('ft_weight', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
    }

    public function setUp()
    {
        $this->hasOne('EvaluationCompany', array(
             'local' => 'eval_id',
             'foreign' => 'eval_id'));

        $this->hasOne('EmployeeMaster as Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('EvaluationFunctionsTaskComments', array(
             'local' => 'ft_id',
             'foreign' => 'ft_id'));
    }
}