<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmpContact extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_contact');
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('con_off_addLine1', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_addLine1_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_addLine1_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_addLine2', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_addLine2_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_addLine2_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_del_postoffice', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_del_postoffice_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_del_postoffice_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_postal_code', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('con_off_country', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_intercom', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_off_vip', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_off_direct', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_off_ext', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_off_fax', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_off_email', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_off_url', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_addLine1', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_addLine1_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_addLine1_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_addLine2', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_addLine2_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_addLine2_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_del_postoffice', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_del_postoffice_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_del_postoffice_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_postal_code', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('con_res_div_sectretariat', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_div_sectretariat_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_div_sectretariat_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_policesation', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_policesation_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_policesation_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_district', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_district_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_district_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_res_phone', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_res_fax', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_res_mobile', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_res_email', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_addLine1', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_addLine1_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_addLine1_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_addLine2', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_addLine2_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_addLine2_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_del_postoffice', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_del_postoffice_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_del_postoffice_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_postal_code', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('con_per_div_sectretariat', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('con_per_div_sectretariat_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_div_sectretariat_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_policesation', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_policesation_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_policesation_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_district', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_district_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_district_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_per_phone', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_per_fax', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_per_mobile', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_per_email', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_addLine1', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_addLine2', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_addLine2_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_addLine2_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_addLine1_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_addLine1_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_postal_code', 'string', 50, array(
             'type' => 'string',
             'length' => '50',
             ));
        $this->hasColumn('con_oth_del_postoffice', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_del_postoffice_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_del_postoffice_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_div_sectretariat', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_div_sectretariat_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_div_sectretariat_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_policesation', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_policesation_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_policesation_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_district', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_district_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_district_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('con_oth_phone', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_oth_fax', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_oth_mobile', 'string', 20, array(
             'type' => 'string',
             'length' => '20',
             ));
        $this->hasColumn('con_oth_email', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}