<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasePayRollEmployeeBank extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_emp_bank');
        $this->hasColumn('bbranch_code', 'string', 6, array(
             'type' => 'string',
             'primary' => true,
             'length' => '6',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('ebank_acc_no', 'string', 80, array(
             'type' => 'string',
             'primary' => true,
             'length' => '80',
             ));
        $this->hasColumn('acctype_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('ebank_amount', 'decimal', 15, array(
             'type' => 'decimal',
             'scale' => '2',
             'length' => '15',
             ));
        $this->hasColumn('ebank_order', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('ebank_active_flag', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('ebank_start_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ebank_end_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ebank_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('PayRollBankAccountType', array(
             'local' => 'acctype_id',
             'foreign' => 'acctype_id'));

        $this->hasOne('PayRollBranch', array(
             'local' => 'bbranch_code',
             'foreign' => 'bbranch_code'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}