<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEBEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_eb_employee');
        $this->hasColumn('ebe_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('ebh_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('ebd_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('ebe_marks', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('ebe_start_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ebe_end_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ebe_complete_date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('ebe_flg_pass', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('ebe_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('ebe_attepmt', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
    }

    public function setUp()
    {
        $this->hasOne('EBMasterHead', array(
             'local' => 'ebh_id',
             'foreign' => 'ebh_id'));

        $this->hasOne('EBMasterDetail', array(
             'local' => 'ebd_id',
             'foreign' => 'ebd_id'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}