<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCustomImport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_custom_import');
        $this->hasColumn('import_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('name', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '250',
             ));
        $this->hasColumn('has_heading', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'length' => '1',
             ));
        $this->hasColumn('fields', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
    }

}