<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEducation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_education');
        $this->hasColumn('edu_code', 'string', 13, array(
             'type' => 'string',
             'primary' => true,
             'length' => '13',
             ));
        $this->hasColumn('edu_name', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_name_si', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('edu_name_ta', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('EmployeeEducation', array(
             'local' => 'edu_code',
             'foreign' => 'edu_code'));
    }
}