<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_users');
        $this->hasColumn('id', 'string', 36, array(
             'type' => 'string',
             'primary' => true,
             'length' => '36',
             ));
        $this->hasColumn('user_name', 'string', 20, array(
             'type' => 'string',
             'default' => '',
             'length' => '20',
             ));
        $this->hasColumn('is_admin', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => '3',
             ));
        $this->hasColumn('user_password', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('emp_number', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('date_entered', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('date_modified', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('modified_user_id', 'string', 36, array(
             'type' => 'string',
             'length' => '36',
             ));
        $this->hasColumn('created_by', 'string', 36, array(
             'type' => 'string',
             'length' => '36',
             ));
        $this->hasColumn('status', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('sm_capability_id', 'integer', 50, array(
             'type' => 'integer',
             'length' => '50',
             ));
        $this->hasColumn('userg_id', 'string', 36, array(
             'type' => 'string',
             'length' => '36',
             ));
        $this->hasColumn('user_prefered_language', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('def_level', 'integer', 20, array(
             'type' => 'integer',
             'length' => '20',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Users as modifiedUser', array(
             'local' => 'modified_user_id',
             'foreign' => 'id'));

        $this->hasMany('Users as createdUser', array(
             'local' => 'id',
             'foreign' => 'created_by'));

        $this->hasOne('UserGroup as userGroup', array(
             'local' => 'userg_id',
             'foreign' => 'userg_id'));

        $this->hasOne('Employee as employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('capability', array(
             'local' => 'sm_capability_id',
             'foreign' => 'sm_capability_id'));

        $this->hasOne('CompanyStructureLevels', array(
             'local' => 'def_level',
             'foreign' => 'def_level'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('Users', array(
             'local' => 'id',
             'foreign' => 'modified_user_id'));

        $this->hasMany('MailNotification', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('TransferRequest', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));
    }
}