<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseHoliday extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_holidays');
        $this->hasColumn('holiday_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('recurring', 'integer', 1, array(
             'type' => 'integer',
             'default' => '0',
             'length' => '1',
             ));
        $this->hasColumn('description', 'string', 2147483647, array(
             'type' => 'string',
             'length' => '2147483647',
             ));
        $this->hasColumn('date', 'date', 25, array(
             'type' => 'date',
             'length' => '25',
             ));
        $this->hasColumn('length', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

}