<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseLeaveType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_leave_type');
        $this->hasColumn('leave_type_id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '20',
             ));
        $this->hasColumn('leave_type_name', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('leave_type_name_si', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('leave_type_name_ta', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasMany('LeaveApplication', array(
             'local' => 'leave_type_id',
             'foreign' => 'leave_type_id'));

        $this->hasMany('LeaveTypeConfig', array(
             'local' => 'leave_type_id',
             'foreign' => 'leave_type_id'));

        $this->hasMany('LeaveEntitlement', array(
             'local' => 'leave_type_id',
             'foreign' => 'leave_type_id'));
    }
}