<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class Basereportmnucapability extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_sm_rpt_mnucapability');
        $this->hasColumn('sm_rpt_capability_id', 'integer', 50, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '50',
             ));
        $this->hasColumn('sm_rpt_mnuitem_id', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
    }

    public function setUp()
    {
        $this->hasMany('reportcapability', array(
             'local' => 'sm_rpt_capability_id',
             'foreign' => 'sm_rpt_capability_id'));
    }
}