<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseTransfer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_transfer');
        $this->hasColumn('trans_id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '8',
             ));
        $this->hasColumn('trans_letter_ld', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('trans_emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('trans_currentdiv_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('trans_div_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('trans_location', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('trans_mutual', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('trans_mu_name', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('trans_effect_date', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
        $this->hasColumn('trans_reason_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('trans_comment', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('trans_prefer_div_id', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
    }

    public function setUp()
    {
        $this->hasOne('TransferReason', array(
             'local' => 'trans_reason_id',
             'foreign' => 'trans_reason_id'));

        $this->hasOne('Employee', array(
             'local' => 'trans_emp_number',
             'foreign' => 'empNumber'));

        $this->hasOne('CompanyStructure', array(
             'local' => 'trans_currentdiv_id',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as TransferPreferCompanyStructure', array(
             'local' => 'trans_prefer_div_id',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as TransferCompanyStructure', array(
             'local' => 'trans_div_id',
             'foreign' => 'id'));

        $this->hasOne('TransferAttach', array(
             'local' => 'trans_id',
             'foreign' => 'trans_id'));

        $this->hasOne('Employee as MutualEmployee', array(
             'local' => 'trans_mu_name',
             'foreign' => 'empNumber'));

        $this->hasMany('TransferRequest', array(
             'local' => 'trans_emp_number',
             'foreign' => 'emp_number'));
    }
}