<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BasepayprocessCapability extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_sm_payproccapbility');
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('prl_type_code', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('prl_disc_code', 'integer', 10, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '10',
             ));
        $this->hasColumn('prl_process_type', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('PayrollType', array(
             'local' => 'prl_type_code',
             'foreign' => 'prl_type_code'));

        $this->hasOne('CompanyStructure', array(
             'local' => 'prl_disc_code',
             'foreign' => 'id'));
    }
}