<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseNoticeEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_notice_employee');
        $this->hasColumn('ns_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('notice_code', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('email', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
        $this->hasColumn('sms', 'string', 1, array(
             'type' => 'string',
             'length' => '1',
             ));
    }

    public function setUp()
    {
        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('Notice', array(
             'local' => 'notice_code',
             'foreign' => 'notice_code'));
    }
}