<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseFormLockDetails extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_formlock_details');
        $this->hasColumn('frmlock_id', 'integer', 255, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '255',
             ));
        $this->hasColumn('mod_id', 'string', 36, array(
             'type' => 'string',
             'length' => '36',
             ));
        $this->hasColumn('con_table_name', 'integer', 200, array(
             'type' => 'integer',
             'length' => '200',
             ));
        $this->hasColumn('con_activity_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('frmlock_form_name', 'integer', 200, array(
             'type' => 'integer',
             'length' => '200',
             ));
        $this->hasColumn('frmlock_form_name_si', 'integer', 200, array(
             'type' => 'integer',
             'length' => '200',
             ));
        $this->hasColumn('frmlock_form_name_ta', 'integer', 200, array(
             'type' => 'integer',
             'length' => '200',
             ));
    }

    public function setUp()
    {
        $this->hasOne('ConcurrencyControl', array(
             'local' => 'con_table_name',
             'foreign' => 'con_table_name'));

        $this->hasOne('Module', array(
             'local' => 'mod_id',
             'foreign' => 'mod_id'));
    }
}