<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEducationEMPHead extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_edu_emp_head');
        $this->hasColumn('eduh_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '11',
             ));
        $this->hasColumn('edu_type_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'length' => '7',
             ));
        $this->hasColumn('grd_year', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('eduh_indexno', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('eduh_institute', 'string', 200, array(
             'type' => 'string',
             'length' => '200',
             ));
        $this->hasColumn('eduh_zscorgdp', 'float', 2147483647, array(
             'type' => 'float',
             'length' => '2147483647',
             ));
        $this->hasColumn('eduh_slrank', 'integer', 11, array(
             'type' => 'integer',
             'length' => '11',
             ));
        $this->hasColumn('eduh_flg', 'integer', 1, array(
             'type' => 'integer',
             'length' => '1',
             ));
        $this->hasColumn('eduh_descreption', 'string', 1000, array(
             'type' => 'string',
             'length' => '1000',
             ));
    }

    public function setUp()
    {
        $this->hasOne('EducationType', array(
             'local' => 'edu_type_id',
             'foreign' => 'edu_type_id'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasMany('EducationEMPDetail', array(
             'local' => 'eduh_id',
             'foreign' => 'eduh_id'));
    }
}