<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseEmpActiveWorkstation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_empacting_workstation');
        $this->hasColumn('emp_number', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('act_job_title_code', 'string', 13, array(
             'type' => 'string',
             'length' => '13',
             ));
        $this->hasColumn('act_workstation_no', 'integer', 7, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '7',
             ));
        $this->hasColumn('act_hie_code_1', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_2', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_3', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_4', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_5', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_6', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_7', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_8', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_9', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_hie_code_10', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
        $this->hasColumn('act_work_satation', 'integer', 6, array(
             'type' => 'integer',
             'length' => '6',
             ));
    }

    public function setUp()
    {
        $this->hasOne('CompanyStructure as act_hie_code_1', array(
             'local' => 'act_hie_code_1',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_2', array(
             'local' => 'act_hie_code_2',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_3', array(
             'local' => 'act_hie_code_3',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_4', array(
             'local' => 'act_hie_code_4',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_5', array(
             'local' => 'act_hie_code_5',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_6', array(
             'local' => 'act_hie_code_6',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_7', array(
             'local' => 'act_hie_code_7',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_8', array(
             'local' => 'act_hie_code_8',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_9', array(
             'local' => 'act_hie_code_9',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure as act_hie_code_10', array(
             'local' => 'act_hie_code_10',
             'foreign' => 'id'));

        $this->hasOne('CompanyStructure', array(
             'local' => 'act_work_satation',
             'foreign' => 'id'));

        $this->hasOne('Employee', array(
             'local' => 'emp_number',
             'foreign' => 'emp_number'));

        $this->hasOne('JobTitle as actjobTitle', array(
             'local' => 'act_job_title_code',
             'foreign' => 'jobtit_code'));
    }
}