<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseRecCvAttachment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_rec_cv_attachment');
        $this->hasColumn('rec_cv_attach_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '20',
             ));
        $this->hasColumn('rec_cv_attach_filename', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '200',
             ));
        $this->hasColumn('rec_cv_attach_size', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '11',
             ));
        $this->hasColumn('rec_cv_attach_attachment', 'mediumblob', null, array(
             'type' => 'mediumblob',
             'notnull' => true,
             ));
        $this->hasColumn('rec_cv_attach_type', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('rec_can_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        $this->hasOne('RecCvAttachment', array(
             'local' => 'rec_can_id',
             'foreign' => 'rec_can_id'));
    }
}