<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseMaritalStatus extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('hs_hr_marital_status');
        $this->hasColumn('marst_code', 'integer', 2, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '2',
             ));
        $this->hasColumn('marst_name', 'string', 30, array(
             'type' => 'string',
             'length' => '30',
             ));
        $this->hasColumn('marst_name_si', 'string', 30, array(
             'type' => 'string',
             'default' => '',
             'length' => '30',
             ));
        $this->hasColumn('marst_name_ta', 'string', 30, array(
             'type' => 'string',
             'default' => '',
             'length' => '30',
             ));
    }

    public function setUp()
    {
        $this->hasMany('Employee', array(
             'local' => 'marst_code',
             'foreign' => 'marst_code'));

        $this->hasMany('EmployeeMaster', array(
             'local' => 'marst_code',
             'foreign' => 'marst_code'));
    }
}