<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class retirementDao extends BaseDao {

    public function readRetirement($id) {
        $q = Doctrine_Query::create()
                        ->select('r.*')
                        ->from('RetirementExtension r')
                        ->where('emp_number = ?', $id);

        return $q->fetchArray();
    }

    public function readRetirementext($id, $rid) {

        $q = Doctrine_Query::create()
                        ->select('r.*')
                        ->from('RetirementExtension r')
                        ->where('emp_number = ?', $id)
                        ->andWhere('ret_id = ?', $rid);

        return $q->fetchArray();
    }

    public function saveRetirement(RetirementExtension $rte) {

        $rte->save();
        return true;
    }

    public function updateRetirement($id, $rid, $fdate, $tdate, $clause, $comment) {

        $q = Doctrine_Query::create()
                        ->update('RetirementExtension r')
                        ->set('r.from_date', '?', $fdate)
                        ->set('r.to_date', '?', $tdate)
                        ->set('r.clause', '?', $clause)
                        ->set('r.comment', '?', $comment)
                        ->where('emp_number = ?', $id)
                        ->andWhere('ret_id = ?', $rid);

        $q->execute();
        return true;
    }

    public function deleteretirement($id, $rid) {

        $q = Doctrine_Query::create()
                        ->delete('RetirementExtension ')
                        ->where('emp_number = ?', $id)
                        ->andWhere('ret_id = ?', $rid);

        $numDeleted = $q->execute();
        if ($numDeleted > 0) {
            return true;
        }
        return false;
    }

    public function readmaxretid($id) {
        $q = Doctrine_Query::create()
                        ->select('MAX(ret_id)')
                        ->from('RetirementExtension r')
                        ->where('r.emp_number = ?', $id);
        return $q->execute();
    }

    public function getEmployeerecord($id) {
        $q = Doctrine_Query::create()
                        ->select('emp_firstname,emp_lastname')
                        ->from('Employee em')
                        ->where('em.emp_number = ?', $id);

        $list = $q->fetchArray();
        return $list;
    }

    public function getRetirementList($orderField = 'r.emp_number', $orderBy = 'ASC', $page = 1) {

        $q = Doctrine_Query::create()
                        ->select('r.*')
                        ->from('RetirementExtension r')
                        ->orderBy($orderField . ' ' . $orderBy);

        // Number of records for a one page
        $resultsPerPage = sfConfig::get('app_items_per_page') ? sfConfig::get('app_items_per_page') : 10;

        // Pager object
        $pagerLayout = new CommonhrmPager(
                        new Doctrine_Pager(
                                $q,
                                $page,
                                $resultsPerPage
                        ),
                        new Doctrine_Pager_Range_Sliding(array(
                            'chunk' => 5
                        )),
                        'retirement/?page={%page_number}'
        );

        $pager = $pagerLayout->getPager();
        $res = array();
        $res['data'] = $pager->execute();
        $res['pglay'] = $pagerLayout;

        return $res;
    }

    public function searchRetiremen($searchMode, $searchValue, $culture='en', $orderField = 'b.from_date', $orderBy = 'ASC', $page = 1) {

        switch ($searchMode) {
            case "emp_name":
                if ($culture == "en")
                    $feildName = "e.emp_display_name";
                else
                    $feildName="e.emp_display_name_" . $culture;
                break;
            case "from_Date":
                $feildName = "b.from_Date";
                break;
            case "to_Date":
                $feildName = "b.to_Date";
                break;
            case "Clause":
                $feildName = "b.Clause";
                break;
        }
        $q = Doctrine_Query::create()
                        ->select('b.*')
                        ->from('RetirementExtension b')
                        ->leftJoin('b.Employee e ON b.emp_number = e.emp_number');

        if ($searchValue != "") {
            $q->where($feildName . ' LIKE ?', '%' . trim($searchValue) . '%');
        }
        $q->orderBy($orderField . ' ' . $orderBy);

        $sysConf = new sysConf();
        $resultsPerPage = $sysConf->getRowLimit() ? $sysConf->getRowLimit() : 10;

        // Pager object
        $pagerLayout = new CommonhrmPager(
                        new Doctrine_Pager(
                                $q,
                                $page,
                                $resultsPerPage
                        ),
                        new Doctrine_Pager_Range_Sliding(array(
                            'chunk' => 5
                        )),
                        "?page={%page_number}&amp;mode=search&amp;searchValue={$searchValue}&amp;searchMode={$searchMode}&amp;sort={$orderField}&amp;order={$orderBy}"
        );

        $pager = $pagerLayout->getPager();
        $res = array();
        $res['data'] = $pager->execute();
        $res['pglay'] = $pagerLayout;

        return $res;
    }

    public function deleteReason($reasonList = array()) {
        if (is_array($reasonList)) {
            $q = Doctrine_Query::create()
                            ->delete('RetirementExtension')
                            ->where('emp_number = ?', $reasonList)
                            ->andWhere('ret_id = ?', $reasonList);

            $numDeleted = $q->execute();
            if ($numDeleted > 0) {
                return true;
            }
            return false;
        }
    }

}

?>
