all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=ictahrmlive'
      username: root
      password: 
      port: 3306
      attributes: { export: tables }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=test_ctahrmlive'
      username: root
      password: hsenidsoft
      port: 3306
