<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property emp_number
 * @property contract_id
 * @property start_date
 * @property end_date
 * @property Employee
 */
class EmpContract extends BaseEmpContract
{

}