<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmployeeLanguage extends BaseEmployeeLanguage
{
//    const FLUENCY_WRITING = 1;
//    const FLUENCY_SPEAKING = 2;
//    const FLUENCY_READING = 3;
//
//    const COMPETENCY_POOR = 1;
//    const COMPETENCE_BASIC = 2;
//    const COMPETENCE_GOOD = 3;
//    const COMPETENCY_MOTHER_TONGUE = 4;
   

}