<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 * @property emp_number
 * @property federal_exceptions
 * @property state_exceptions
 * @property federal_status
 * @property state
 * @property state_status
 * @property unemp_state
 * @property work_state
 * @property Employee
 */
class EmpUsTax extends BaseEmpUsTax {

	const TAX_STATUS_MARRIED = "M";
	const TAX_STATUS_SINGLE = "S";
	const TAX_STATUS_NONRESIDENTALIEN = "NRA";
	const TAX_STATUS_NOTAPPLICABLE = "NA";

}