<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalaryGrade extends BaseSalaryGrade
{
    public function GetCurrencyDetail($currencyCode) {

        $currencyDetail = null;

        foreach ($this->SalaryCurrencyDetail as $currency) {
            if ($currency->currency_id == $currencyCode) {
                $currencyDetail = $currency;
                break;
            }
        }

        return ($currencyDetail);
    }
}