-- stored procedure definition script spprocessnetpay for mysql
-- generated by (c) ispirer sqlways express 5.0 build 901
-- timestamp: fri oct 21 11:43:32 2011

delimiter //

drop procedure if exists spprocessnetpay;
//
create  procedure spprocessnetpay(start_date datetime,            
end_date datetime,           
empnumber varchar(6),        
grosssalary numeric(13,2))
 
begin

   declare sbasecurr varchar(6);
   
  
   select
   gn.emp_number, grosssalary+(grossnet -ifnull(totwebloan,0)) as netpay
   from(select
      e.emp_number,ifnull(ag.trn_proc_emp_amt,0) -ifnull(dg.trn_proc_emp_amt,0) as grossnet
      from(hs_pr_employee e
      left join(select
         p.emp_number,ifnull(sum(trn_proc_emp_amt),0) as trn_proc_emp_amt
         from
         hs_pr_processedtxn p,hs_pr_transaction_details d,hs_pr_transaction_type t
         where p.trn_dtl_code = d.trn_dtl_code and t.trn_typ_code = d.trn_typ_code 
         and  p.trn_startdate  = start_date and p.trn_enddate = end_date
         and  p.emp_number = empnumber and (erndedcon = 1 or erndedcon = 2 )
         and trn_dtl_addtonetpay = 1
         group by p.emp_number) ag
      on e.emp_number = ag.emp_number )
      left join(select p.emp_number,ifnull(sum(trn_proc_emp_amt),0) as trn_proc_emp_amt
         from hs_pr_processedtxn p,hs_pr_transaction_details d,hs_pr_transaction_type t
         where p.trn_dtl_code = d.trn_dtl_code and t.trn_typ_code = d.trn_typ_code
         and  p.trn_startdate  = start_date and p.trn_enddate  = end_date
         and  p.emp_number = empnumber and (erndedcon = -1 or erndedcon = 0) and trn_dtl_addtonetpay = 1
         group by p.emp_number) dg
      on e.emp_number = dg.emp_number where e.emp_number = empnumber) gn 
	   left join(select s.emp_number,
   sum(coalesce(s.ln_sch_inst_amount,0)) totwebloan
      from hs_ln_schedule s,hs_pr_employee e
      where s.emp_number = e.emp_number and
      ln_sch_is_processed = 1  and ln_sch_proc_from_date = start_date and ln_sch_proc_to_date = end_date and
      s.emp_number = empnumber
      group by s.emp_number) sl
   on gn.emp_number = sl.emp_number;
end;
     

-- </fndbuid>
//

delimiter ;

